version: "3.4"

services:

  registry:
    build: backend/registry
    container_name: finance-registry
    ports:
      - 8762:8761

  edge:
    build: backend/edge
    container_name: finance-edge
    depends_on:
      - registry
    ports:
      - 8081:8080

  backend:
    build: backend
    container_name: finance-backend
    depends_on:
      - registry
      - db
      - activemq
    ports:
      - 8091:8090

  db:
    build: db
    container_name: finance-db
    ports:
      - 3307:3306

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - 61617:61616
