version: "3.4"

services:

  backend:
    build: backend
    container_name: finance-backend
    depends_on:
      - db
    ports:
      - 8091:8090

  db:
    build: db
    container_name: finance-db
    ports:
      - 3307:3306
