version: "3"

services:

  backend:
    build: backend
    depends_on:
      - db
    ports:
      - "8081:8090"

  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_finance
    volumes:
      - ./db/dump.sql:docker-entrypoint-initdb.d/dump.sql
